<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <RootNamespace>SuperMech</RootNamespace>
    <AssemblyName>超神机械师</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\StreamingAssets\mods\NML\Assemblies\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\StreamingAssets\mods\NML\Assembly-CSharp-Publicized.dll</HintPath>
    </Reference>
    <Reference Include="NeoModLoader">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\StreamingAssets\mods\NeoModLoader.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="SQLite">
      <HintPath>E:\Ksoftware\STEAM\steamapps\common\worldbox\worldbox_Data\Managed\SQLite.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>